<a href="https://colab.research.google.com/github/britjet/Linear-Algebra_ChE_2nd-sem-2021-2022/blob/main/Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Laboratory 6: Matrix Operation

Objectives

At the end of this activity you will be able to:

1. Understand the fundamental matrix operations.
2. Solve intermediate equations using the procedures.
3. In engineering solutions, use matrix algebra.

##Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

##Transposition

Transposition is a fundamental operation in matrix algebra and is one of its most critical applications. The transposition of a matrix is accomplished by flipping its members' values over the matrix's diagonals. The rows and columns of the original matrix will be swapped due to this. As a result, the symbol $A^T$ indicates the transpose of matrix $A$. As an illustration, consider the following:

$$A = \begin{bmatrix} 2 & 5 & 8\\5 & -6 &1 \\ 10 & -8 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 2 & 3 & 8\\5 & -1 &-9 \\ 7 & 10 & 5\end{bmatrix}$$

This may now be accomplished programmatically through the use of the np.transpose() function or the T method.

In [2]:
A = np.array([
    [3 ,9, 7],
    [4, -5, 0],
    [5, -2, 5]
])
A

array([[ 3,  9,  7],
       [ 4, -5,  0],
       [ 5, -2,  5]])

In [3]:
AT1 = np.transpose(A)
AT1

array([[ 3,  4,  5],
       [ 9, -5, -2],
       [ 7,  0,  5]])

In [4]:
AT2 = A.T
AT2

array([[ 3,  4,  5],
       [ 9, -5, -2],
       [ 7,  0,  5]])

In [5]:
np.array_equiv(AT1, AT2)

True

In [6]:
B = np.array([
    [2,4,6,8],
    [3,6,9,12],
])
B.shape

(2, 4)

In [7]:
np.transpose(B).shape

(4, 2)

In [8]:
B.T.shape

(4, 2)

#### Create your own matrix (you can experiment with non-squares) and use it to test transposition.

In [9]:
## Try out your code here.
Z=np.array([
    [5,7,9],
    [4,8,10]        
])
Z.shape

(2, 3)

In [10]:
np.transpose(Z).shape

(3, 2)

In [11]:
Z.T.shape

(3, 2)

In [12]:
ZT = Z.T
ZT

array([[ 5,  4],
       [ 7,  8],
       [ 9, 10]])

## Dot Product / Inner Product

Assuming you are familiar with the dot product from a previous laboratory activity, we will attempt to do the same operation using matrices. The Dot Product/Inner Product will obtain the sum of products of the vectors by row-column pairs by performing a matrix dot product operation. As an example, consider the following two matrices: $X$ and $Y$.

$$X = \begin{bmatrix}x_{(1,1)}&x_{(3,3)}\\ x_{(5,8)}&x_{(5,5)}\end{bmatrix}, Y = \begin{bmatrix}y_{(1,1)}&y_{(3,3)}\\ y_{(5,8)}&y_{(5,5)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(1,1)}*y_{(1,1)} + x_{(3,3)}*y_{(5,8)} & x_{(1,1)}*y_{(3,3)} + x_{(3,3)}*y_{(5,5)} \\  x_{(5,8)}*y_{(1,1)} + x_{(5,5)}*y_{(5,8)} & x_{(5,8)}*y_{(3,3)} + x_{(5,5)}*y_{(5,5)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}2&3\\ 1&2\end{bmatrix}, Y = \begin{bmatrix}-2&0\\ 4&4\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 2*-2 + 3*4 & 2*0 + 4*4 \\  0*-2 + 2*3 & 0*0 + 2*4 \end{bmatrix} = \begin{bmatrix} 8 & 16 \\ 6 & 8 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [13]:
X = np.array([
    [0,3],
    [5,8]
])
Y = np.array([
    [-5,8],
    [0,7]
])

In [14]:
np.array_equiv(X, Y)

False

In [15]:
np.dot(X,Y)

array([[  0,  21],
       [-25,  96]])

In [16]:
X.dot(Y)

array([[  0,  21],
       [-25,  96]])

In [17]:
X @ Y

array([[  0,  21],
       [-25,  96]])

In [18]:
np.matmul(X,Y)

array([[  0,  21],
       [-25,  96]])

In [19]:
D = np.array([
    [5,8,12],
    [2,8,3],
    [5,9,1]
])
E = np.array([
    [-5,0,9],
    [5,8,6],
    [7,1,3]
])

In [20]:
D @ E

array([[ 99,  76, 129],
       [ 51,  67,  75],
       [ 27,  73, 102]])

In [21]:
D.dot(E)

array([[ 99,  76, 129],
       [ 51,  67,  75],
       [ 27,  73, 102]])

In [22]:
np.matmul(D, E)

array([[ 99,  76, 129],
       [ 51,  67,  75],
       [ 27,  73, 102]])

In [23]:
np.dot(D, E)

array([[ 99,  76, 129],
       [ 51,  67,  75],
       [ 27,  73, 102]])

When comparing matrix dot products to vector dot products, there are certain extra criteria to follow. Due to the fact that vector dot products were just in one dimension, there are less limitations. Because we are now working with Rank 2 vectors, we must take into consideration the following rules:

###In order for the two matrices in question to be equivalent, the inner dimensions of each matrix must be the same.

Consider the following scenario: you have a matrix $A$ with the structure of $(a,b)$, where $a$ and $b$ are any integers. Suppose we want to conduct a dot product between $A$ and another matrix $B$, then matrix $B$ should have the shape $(b,c)$, where $b$ and $c$ may be any integers and $A$ can be any other integer. As an example, consider the following matrices:

$$A = \begin{bmatrix}3&1\\8&-5\\1&8\end{bmatrix}, B = \begin{bmatrix}1&4\\8&6\\-2&-3\end{bmatrix}, C = \begin{bmatrix}2&9&5\\3&4&5\end{bmatrix}$$

$A$ has the shape $(,)$, $B$ has the shape $(,)$, and $C$ has a shape of $(,)$ in this example. As a result, the only matrix pairings that are qualified to conduct dot product are the matrices $A cdot C$ and $B cdot C$, respectively.

In [24]:
A = np.array([
    [3, 1],
    [8, -5],
    [1, 8]
])
B = np.array([
    [1,4],
    [8,6],
    [-2,-3]
])
C = np.array([
    [2,9,5],
    [3,4,5]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [25]:
A @ C

array([[ 9, 31, 20],
       [ 1, 52, 15],
       [26, 41, 45]])

In [26]:
B @ C

array([[ 14,  25,  25],
       [ 34,  96,  70],
       [-13, -30, -25]])

If you look closely, you will note that the geometry of the dot product has changed and that it is no longer the same as any of the matrices that we utilized. In reality, the form of a dot product is generated by the shapes of the matrices that were utilized. As an example, consider the shapes of the matrices $A$ and $B$: $(a,b)$ and $(b,c)$, respectively. In this case, the shape of $A\cdot B$ should be $(a,c)$.

In [27]:
A @ B.T

array([[  7,  30,  -9],
       [-12,  34,  -1],
       [ 33,  56, -26]])

In [28]:
X = np.array([
    [2,4,5,10]
])
Y = np.array([
    [6,1,8,-5]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [29]:
Y.T @ X

array([[ 12,  24,  30,  60],
       [  2,   4,   5,  10],
       [ 16,  32,  40,  80],
       [-10, -20, -25, -50]])

In [30]:
X @ Y.T

array([[6]])

Moreover, you can see that when you attempt to multiply A and B, the program produces the error `ValueError` due to a mismatch in the matrix structure.

### Rule 2: Dot Product has special properties

Due to the fact that dot products are common in matrix algebra, it follows that they have numerous distinct qualities that should be taken into consideration while formulating solutions:

 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [31]:
A = np.array([
    [2,5,5],
    [4,7,6],
    [7,4,1]
])
B = np.array([
    [3,1,9],
    [4,3,6],
    [4,8,8]
])
C = np.array([
    [9,1,4],
    [0,5,8],
    [7,5,1]
])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
A.dot(np.eye(3))

array([[2., 5., 5.],
       [4., 7., 6.],
       [7., 4., 1.]])

In [34]:
np.array_equal(A@B, B@A)

False

In [35]:
E = A @ (B @ C)
E

array([[1030,  771,  728],
       [1458, 1059,  966],
       [1034,  651,  475]])

In [36]:
F = (A @ B) @ C
F

array([[1030,  771,  728],
       [1458, 1059,  966],
       [1034,  651,  475]])

In [37]:
np.array_equal(E, X)

False

In [38]:
np.array_equiv(E, F)

True

In [39]:
np.eye(A)

TypeError: ignored

In [40]:
A @ E

array([[14520, 10092,  8661],
       [20530, 14403, 12524],
       [14076, 10284,  9435]])

In [41]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.array_equal(a_dot_z,z_mat)

True

In [44]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

##Determinant

A determinant is a scalar value that may be obtained from a square matrix in two dimensions. Determinants are important values in matrix algebra because they are fundamental and important values. Although it will not be immediately apparent in this laboratory how it might be used in practice, it will be extensively utilized in subsequent lectures.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}2&5\\7&9\end{bmatrix}, |A| = $$
However, you may question what happens to square matrices that are not of the form $(2,2)$. We may address this issue in a variety of ways, including utilizing co-factor expansion and the minors technique, among others. In the laboratory, we can learn how to do this in the lecture, but we can also programmatically compute the difficult calculation of high-dimensional matrices by using Python. This may be accomplished by the use of the function `np.linalg.det()`.


In [45]:
A = np.array([
    [2,5],
    [7,9]
])
np.linalg.det(A)

-17.0

In [46]:
B = np.array([
              [2, 1, 3],
              [3, -6 ,-7],
              [0, -1, 4]
])
np.linalg.det(B)

-83.00000000000003

In [47]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [3,9,7,4],
    [3,6,8,3],
    [3,9,8,2],
    [7,5,5,2]
])
np.linalg.det(B)

318.0

##Inverse

The inverse of a matrix is yet another important operation in matrix algebra that should not be overlooked. Determining the inverse of a matrix allows us to assess whether or not the matrix is solvable and has the characteristics of a system of linear equations — we'll go into more detail about this in the nect module. Another use of the inverse matrix is in the solution of the issue of divisibility between matrices between two variables. Although there is an element-by-element division method, there is no such method for splitting the whole idea of matrices. It is possible that the idea of "dividing" matrices is the same as that of "inverting" matrices in the case of inverse matrices.

After that, we must go through various processes to get the inverse of the matrix we have created. So, let us suppose we have the following matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
It is possible that you will need to apply co-factors, minors, adjugates, and other reduction techniques for higher-dimension matrices. We can use a computer program to address this problem.`np.linalg.inv()`.

In [49]:
M = np.array([
    [1,7],
    [-3,5 ]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [50]:
P = np.array([
              [2, 5, 8],
              [3, 6, -9],
              [1, 4, 7]
])
Q = np.linalg.inv(P)
Q

array([[ 1.44444444, -0.05555556, -1.72222222],
       [-0.55555556,  0.11111111,  0.77777778],
       [ 0.11111111, -0.05555556, -0.05555556]])

In [51]:
P @ Q

array([[ 1.00000000e+00,  1.11022302e-16, -1.11022302e-16],
       [ 4.99600361e-16,  1.00000000e+00, -2.49800181e-16],
       [ 5.55111512e-17,  8.32667268e-17,  1.00000000e+00]])

In [52]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [62]:
squad = np.array([
    [1.5, 1.0, 2.5],
    [0.8, 0.1, 1.9],
    [0.1, 0.5, 3.0]
])
weights = np.array([
    [1.2, 0.3, 0.9]
])
p_grade = squad @ weights.T
p_grade


array([[4.35],
       [2.7 ],
       [2.97]])

##Activity

###Task 1

In [63]:
N = np.array([
       [8, 6, 1, 5],
       [6, 7, 1, 0],
       [9, 0, 8, 8],
       [-8, 9, 2, 3]
])
T = np.array([
       [6, 6, 1, 2],
       [6, 5, 9, 2],
       [4, 9, 8, -4],
       [-1, 9, 7, 2]
])
G = np.array([
       [5, 1, -5, 2],
       [0, 0, 9, 5],
       [-4, -9, 3, 8],
       [-7, 5, 1, 0]
])

 $A \cdot B \neq B \cdot A$

In [64]:
T = (N@T) !=(T@N)
T

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

$A \cdot (B \cdot C) = (A \cdot B) \cdot C$



In [65]:
A = N @ (T@G)
A

array([[-120,  -60,  160,  300],
       [ -84,  -42,  112,  210],
       [-150,  -75,  200,  375],
       [ -36,  -18,   48,   90]])

In [66]:
B = (N @ T) @ G
B

array([[-120,  -60,  160,  300],
       [ -84,  -42,  112,  210],
       [-150,  -75,  200,  375],
       [ -36,  -18,   48,   90]])

 $A\cdot(B+C) = A\cdot B + A\cdot C$:


In [67]:
C = N @ (T + G)
C

array([[ 21,  44,  42,  74],
       [ 40,  11,  50,  69],
       [-18,   2,  12, 107],
       [-63,  -5, 136,  51]])

In [69]:
D = (N@T) + (N@G)
D

array([[ 21,  44,  42,  74],
       [ 40,  11,  50,  69],
       [-18,   2,  12, 107],
       [-63,  -5, 136,  51]])

$(B+C)\cdot A = B\cdot A + C\cdot A$

In [70]:
E = (T+G) @ N
E

array([[   0,   77,  -18,    7],
       [  56,   67,   94,  103],
       [-108,    7,   39,   44],
       [  -2,   15,   18,  -11]])

In [71]:
F = (T@N) + (G@N)
F

array([[   0,   77,  -18,    7],
       [  56,   67,   94,  103],
       [-108,    7,   39,   44],
       [  -2,   15,   18,  -11]])

$A\cdot I = A$

In [72]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [74]:
N.dot(np.eye(4))

array([[ 8.,  6.,  1.,  5.],
       [ 6.,  7.,  1.,  0.],
       [ 9.,  0.,  8.,  8.],
       [-8.,  9.,  2.,  3.]])

$A\cdot \emptyset = \emptyset$ 

In [77]:
z_mat = np.zeros(G.shape)
z_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

##Conclusion

The students demonstrated an understanding of and ability to use a variety of matrix operations, including transpository, dot product, determinant, and inverse. Students demonstrated their ability to put their learning into practice by successfully completing the task, which required them to create and execute the six multiplications characteristics.