<a href="https://colab.research.google.com/github/britjet/Linear-Algebra_ChE_2nd-sem-2021-2022/blob/main/Inverse%20Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


##Transposition

meaning

$$A = \begin{bmatrix} -2 & 3 & -4 \\ 3 & -2 & 1 \\ 2 & -1 & 3 \end{bmatrix}
$$

$$A^T = \begin{bmatrix} -2 & 3 & -4 \\ 3 & -2 & 1 \\ 2 & -1 & 3 \end{bmatrix}
$$

explain

In [2]:
A = np.array([
    [2,4,6],
    [3,6,9],
    [0,1,3]
])
A

array([[2, 4, 6],
       [3, 6, 9],
       [0, 1, 3]])

In [3]:
AT1 = np.transpose(A)
AT1

array([[2, 3, 0],
       [4, 6, 1],
       [6, 9, 3]])

In [4]:
AT2 = A.T
AT2

array([[2, 3, 0],
       [4, 6, 1],
       [6, 9, 3]])

In [5]:
np.array_equiv(AT1, AT2)

True

In [6]:
B = np.array([
    [3,9,7],
    [4,2,5],
])
B.shape

(2, 3)

In [7]:
np.transpose(B).shape

(3, 2)

In [8]:
B.T. shape

(3, 2)

#Dot Product 

explaination

In [9]:
X = np.array([
    [3,9],
    [0,9]
])
Y = np.array([
    [-9,5],
    [5,5]
])

In [10]:
np.array_equiv(X, Y)

False

In [11]:
np.dot(X, Y)

array([[18, 60],
       [45, 45]])

In [13]:
X.dot(Y)

array([[18, 60],
       [45, 45]])

In [12]:
X @ Y

array([[18, 60],
       [45, 45]])

##Rule 1: The 

In [ ]:
A @ B.T

In [ ]:
X = np.array([
    [2,5,8,9]
])
Y = np.array([
   [3,6,9,10]
])
print(X.shape)
print(Y.shape)

In [ ]:
A = np.array([
    [5,6],
    [3,8],
    [0,8]
])
B = np.array([
    [5,9],
    [4,6],
    [-3,-8]
])
C = np.array([
    [2,8],
    [3,6]
])
print(A.shape)
print(B.shape)
print(C.shape)


In [ ]:
A @ C

In [ ]:
B @ C

In [14]:
A = np.array([
    [3,5],
    [5,9]
])
np.linalg.det(A)

2.0000000000000013

In [15]:
B = np.array([
              [0,1,4],
              [7,2,5],
              [5,8,9]
])
np.linalg.det(B)

146.0

In [ ]:
K = np.array([
              [7,8,9],
              [4,5,6],
              [-2,-8,-1]
])
L = np.linalg.inv(K)
L

In [ ]:
K @ L