<a href="https://colab.research.google.com/github/britjet/Linear-Algebra_ChE_2nd-sem-2021-2022/blob/main/Matrix_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment in ChE

# Objectives
At the end of this activity you will be able to:
1. Understand the concept of matrices and how they relate to linear equations.
2. Basic matrix computations are performed.
3. Python is a programming language that may be used to program and interpret matrix equations and operations.



##Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline


###Matrices
The usage and notation of matrices are most likely one of the basics of contemporary computing. Matrices are also helpful in representing complicated equations or several interconnected equations, ranging from 2-dimensional equations to hundreds of thousands.


Assume you have A and B as a system of equations.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        8x - 20y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        1x -27y -5z \\
        -2x + 6y +9z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        w-12x+8y-2z \\ 
        8w - x -15y + 3z \\
        4w -x +13y -6z
    \end{array}
\right. $$



We can see that A is a two-parameter system comprising two equations. B, on the other hand, is a three-equation system with three parameters. They may be represented as matrices as follows:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2 \end{bmatrix}
$$


Let's assume that you've previously covered the basic representation of matrices, their types, and the operations they perform. Then we may proceed. We'll get to work on them in Python right now.

###Declaring Matrices

To describe the system of linear equations, we'll use a matrix similar to what we did in our prior laboratory exercise. The entities or numbers that make up matrices are the matrix's elements. A matrix's the list/array-like structure is formed by arranging and ordering these components in rows and columns, creating the list/array structure. These objects are indexed similarly to arrays, based on their row and column numbers. As seen in the equation below, this may be stated mathematically in a number of ways. A, on the other hand, is a matrix containing components indicated by the letters aij. The matrix's row and column counts are indicated by the letters i and j, respectively. It is important to remember that the size of a matrix is *i x j.*

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


We went over some of the different kinds of matrices as vectors in the last lab activity, but we'll go over them in more detail in this one. Because you already know how to define a vector using the **shape, dimension, and size** properties, we'll utilize those same qualities to examine these matrices in the next section.

In [ ]:
## Since we'll keep on describing kmatrices. Let's make a function.

In [5]:
## Since we'll keep on describing kmatrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')


In [ ]:
##Declaring 2 x 2 matrix
A = np.array([
       [2, 8],
       [9, 15]
])
describe_mat(A)

In [8]:
G = np.array([
    [11,16,25],
    [2,8,17]
])
describe_mat(G)


Matrix:
[[11 16 25]
 [ 2  8 17]]

Shape:	(2, 3)
Rank:	2



In [9]:
## Declaring a 3 x 2 matrix
B =  np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)


Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [10]:
H = np.array([1,2,3,4])
describe_mat(H)

Matrix:
[1 2 3 4]

Shape:	(4,)
Rank:	1



# Categorizing Matrices

Matrix classification may be accomplished in a variety of ways. One might be following their **element values**, while the other could be by their **shape**. We'll make an effort to go through them.

### According to shape

### Row and Column Matrices

In vector and matrix computing, row and column matrices are often encountered. It is possible to use them to represent a larger vector space's row and column spaces. Individual columns or rows represent the row and column matrices, respectively. As a result, the form of row matrices would be* 1 x j*, whereas the shape of column matrices would be *i x 1*, as seen below.

In [11]:
## Declaring a Row Matrix

rowmatrix1D = np.array([
    1, 3, 2, -4
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3, -4]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)


Matrix:
[ 1  3  2 -4]

Shape:	(4,)
Rank:	1

Matrix:
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2



In [12]:
col_mat = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)


Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



###Square Matrices

They have the same row and column sizes as one another, as defined above. If i=j, we may argue that a matrix is square. To determine square matrices, we may modify our matrix descriptor function.

In [15]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')


In [16]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)


Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False



### According to element values

### Null Matrix

A Null Matrix is a matrix that contains no elements. It is always a subspace of a vector or matrix of any kind of data.

In [18]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')


In [19]:
null_mat = np.array([])
describe_mat(null_mat)


Matrix is Null


### Zero Matrix

A zero matrix may be any rectangular matrix, but it must have all of its members have the value zero to be considered.

In [20]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


###Ones Matrix

One's matrixes are similar in appearance to zero matrices in that they may be any rectangular matrix with all of its elements being one's instead of zero's.

In [21]:
ones_mat_row = np.zeros((1,2))
ones_mat_sqr = np.zeros((2,2))
ones_mat_rct = np.zeros((3,2))

print(f'Ones Row Matrix: \n{zero_mat_row}')
print(f'Ones Square Matrix: \n{zero_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{zero_mat_rct}')


Ones Row Matrix: 
[[0. 0.]]
Ones Square Matrix: 
[[0. 0.]
 [0. 0.]]
Ones Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


###Diagonal Matrix

It is a square matrix that contains values only on the diagonal of the matrix, which is known as the diagonal matrix.

In [23]:
np.array([
        [2, 0, 0],
        [0, 3, 0],
        [0, 0, 5]
])
# a[1, 1], a[2, 2], a[3, 3],  ... a[n-1, n-1]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [24]:
d = np.diag([2,3,5,7])
#d.shape[0]==d.shape[1]
d

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

#Identity Matrix

An identity matrix is a specific diagonal matrix in which the values at the diagonal are all one. An identity matrix may be represented as.

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#Upper triangular matrix

An upper triangular matrix is a matrix which has no values below the diagonal and is composed of three rows and three columns.

In [28]:
np.array([
          [1,2,3,4],
          [0,3,1,-1],
          [0,0,1,2],
          [0,0,0,2]
])

array([[ 1,  2,  3,  4],
       [ 0,  3,  1, -1],
       [ 0,  0,  1,  2],
       [ 0,  0,  0,  2]])

In [29]:
F = np.array([
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
])
np.triu(F)


array([[ 2, -3,  4, -5,  6],
       [ 0, -3,  4, -5,  6],
       [ 0,  0,  4, -5,  6],
       [ 0,  0,  0, -5,  6],
       [ 0,  0,  0,  0,  6]])

In [31]:
F = np.array([
              [2, -3, 4, -5,6],
              [2, -3, 4, -5,6],
              [2, -3, 4, -5,6],
              [2, -3, 4, -5,6],
              [2, -3, 4, -5,6],
])
np.triu(F)

array([[ 2, -3,  4, -5,  6],
       [ 0, -3,  4, -5,  6],
       [ 0,  0,  4, -5,  6],
       [ 0,  0,  0, -5,  6],
       [ 0,  0,  0,  0,  6]])

#Lower Triangular Matrix

A lower triangular matrix is a matrix that has no values that are higher than the diagonal of the matrix.

In [34]:
np.tril(F)

array([[ 2,  0,  0,  0,  0],
       [ 2, -3,  0,  0,  0],
       [ 2, -3,  4,  0,  0],
       [ 2, -3,  4, -5,  0],
       [ 2, -3,  4, -5,  6]])

In [33]:
np.array([
          [1,0,0],
          [5,3,0],
          [7,8,5]
])

array([[1, 0, 0],
       [5, 3, 0],
       [7, 8, 5]])